/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IsNOROOLD, IsNOROOLDInterface } from "../IsNOROOLD";

const _abi = [
  {
    inputs: [],
    name: "INDEX",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IsNOROOLD__factory {
  static readonly abi = _abi;
  static createInterface(): IsNOROOLDInterface {
    return new utils.Interface(_abi) as IsNOROOLDInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IsNOROOLD {
    return new Contract(address, _abi, signerOrProvider) as IsNOROOLD;
  }
}
